var commonMsg = {
	alert_user_not_registered: 'You are not registered.. please signUp First',
	alert_signUp_success: 'You have successfully registered... plz continue with login',
	alert_country_search: 'Please choose Country  from the given list',
	alert_District_search: 'Please choose  District from the given list',
	alert_Contact_Success: 'Thank You for Contact us, we will get bact to you sortly',
	label_signUp: 'New User????? Sign Up Please',
	label_updateProfle: 'Update Your Profile',
	label_edit_this_page: 'Edit this Page',
	label_modal_header: 'Editing',
	label_edit_page: 'Edit This Page',
	label_save_page: 'Save This Page',
	label_login: 'Login to your account',
	label_select_org: 'Select Your Organization',
	label_signUp_coach: 'Create your own website... for that you need to sign up first',
	confirm_delete: 'Are You sure you want to delete',
	map_error: 'your browser doesnt support geolocation',
	error_length_greater_30: 'Length of Link can not be greater than 30',
	error_length_greater_50: 'Length of Link can not be greater than 50',
	error_server: 'There is some server error , make sure entered email is unique',
	error_required: 'This Field can not be empty',
	disp_addlistItem: 'Add List Item',
	disp_addInnerItem: 'Add Inner Item',
	disp_creation_of_link: 'Creation of Link',
	disp_link_name: 'Link Name',
	edit_content: {
		link: 	'Name Of Link',
		header: 'Header',
		desc: 	'Description',
		readMore: 'Read More Content',
		image: 'Image',
		side: 'Bottom Header',
		middle: 'Content of bottom header'
	}
}
var msg = commonMsg;
